/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class SqlQueryDslQuickfixProvider extends XbaseQuickfixProvider {
}
