/*
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SqlQueryDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/dc/sql/lang/parser/antlr/internal/InternalSqlQueryDsl.tokens");
	}
}
