/*
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class SqlQueryDslEditor extends XbaseEditor {
}
