/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.dc.sql.lang.SqlQueryDslRuntimeModule;
import de.dc.sql.lang.SqlQueryDslStandaloneSetup;
import de.dc.sql.lang.ide.SqlQueryDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SqlQueryDslIdeSetup extends SqlQueryDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    SqlQueryDslRuntimeModule _sqlQueryDslRuntimeModule = new SqlQueryDslRuntimeModule();
    SqlQueryDslIdeModule _sqlQueryDslIdeModule = new SqlQueryDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_sqlQueryDslRuntimeModule, _sqlQueryDslIdeModule));
  }
}
