/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.ide;

import de.dc.sql.lang.ide.AbstractSqlQueryDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SqlQueryDslIdeModule extends AbstractSqlQueryDslIdeModule {
}
