/*
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SqlQueryDslProposalProvider extends AbstractSqlQueryDslProposalProvider {
}
