/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.scoping;

import de.dc.sql.lang.scoping.AbstractSqlQueryDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SqlQueryDslScopeProvider extends AbstractSqlQueryDslScopeProvider {
}
