/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.sqlQueryDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.dc.sql.lang.sqlQueryDsl.Model#getPackage <em>Package</em>}</li>
 *   <li>{@link de.dc.sql.lang.sqlQueryDsl.Model#getName <em>Name</em>}</li>
 *   <li>{@link de.dc.sql.lang.sqlQueryDsl.Model#getQueries <em>Queries</em>}</li>
 * </ul>
 *
 * @see de.dc.sql.lang.sqlQueryDsl.SqlQueryDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package</em>' attribute.
   * @see #setPackage(String)
   * @see de.dc.sql.lang.sqlQueryDsl.SqlQueryDslPackage#getModel_Package()
   * @model
   * @generated
   */
  String getPackage();

  /**
   * Sets the value of the '{@link de.dc.sql.lang.sqlQueryDsl.Model#getPackage <em>Package</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Package</em>' attribute.
   * @see #getPackage()
   * @generated
   */
  void setPackage(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.dc.sql.lang.sqlQueryDsl.SqlQueryDslPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.dc.sql.lang.sqlQueryDsl.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Queries</b></em>' containment reference list.
   * The list contents are of type {@link de.dc.sql.lang.sqlQueryDsl.Query}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Queries</em>' containment reference list.
   * @see de.dc.sql.lang.sqlQueryDsl.SqlQueryDslPackage#getModel_Queries()
   * @model containment="true"
   * @generated
   */
  EList<Query> getQueries();

} // Model
