/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.sqlQueryDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.xtext.common.types.JvmFormalParameter;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.dc.sql.lang.sqlQueryDsl.Query#getName <em>Name</em>}</li>
 *   <li>{@link de.dc.sql.lang.sqlQueryDsl.Query#getParameters <em>Parameters</em>}</li>
 *   <li>{@link de.dc.sql.lang.sqlQueryDsl.Query#getStatement <em>Statement</em>}</li>
 *   <li>{@link de.dc.sql.lang.sqlQueryDsl.Query#isStatementFromFile <em>Statement From File</em>}</li>
 *   <li>{@link de.dc.sql.lang.sqlQueryDsl.Query#getFilePath <em>File Path</em>}</li>
 * </ul>
 *
 * @see de.dc.sql.lang.sqlQueryDsl.SqlQueryDslPackage#getQuery()
 * @model
 * @generated
 */
public interface Query extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.dc.sql.lang.sqlQueryDsl.SqlQueryDslPackage#getQuery_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.dc.sql.lang.sqlQueryDsl.Query#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.xtext.common.types.JvmFormalParameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see de.dc.sql.lang.sqlQueryDsl.SqlQueryDslPackage#getQuery_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<JvmFormalParameter> getParameters();

  /**
   * Returns the value of the '<em><b>Statement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement</em>' attribute.
   * @see #setStatement(String)
   * @see de.dc.sql.lang.sqlQueryDsl.SqlQueryDslPackage#getQuery_Statement()
   * @model
   * @generated
   */
  String getStatement();

  /**
   * Sets the value of the '{@link de.dc.sql.lang.sqlQueryDsl.Query#getStatement <em>Statement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement</em>' attribute.
   * @see #getStatement()
   * @generated
   */
  void setStatement(String value);

  /**
   * Returns the value of the '<em><b>Statement From File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement From File</em>' attribute.
   * @see #setStatementFromFile(boolean)
   * @see de.dc.sql.lang.sqlQueryDsl.SqlQueryDslPackage#getQuery_StatementFromFile()
   * @model
   * @generated
   */
  boolean isStatementFromFile();

  /**
   * Sets the value of the '{@link de.dc.sql.lang.sqlQueryDsl.Query#isStatementFromFile <em>Statement From File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement From File</em>' attribute.
   * @see #isStatementFromFile()
   * @generated
   */
  void setStatementFromFile(boolean value);

  /**
   * Returns the value of the '<em><b>File Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File Path</em>' attribute.
   * @see #setFilePath(String)
   * @see de.dc.sql.lang.sqlQueryDsl.SqlQueryDslPackage#getQuery_FilePath()
   * @model
   * @generated
   */
  String getFilePath();

  /**
   * Sets the value of the '{@link de.dc.sql.lang.sqlQueryDsl.Query#getFilePath <em>File Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File Path</em>' attribute.
   * @see #getFilePath()
   * @generated
   */
  void setFilePath(String value);

} // Query
