/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.validation;

import de.dc.sql.lang.validation.AbstractSqlQueryDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SqlQueryDslValidator extends AbstractSqlQueryDslValidator {
}
