/*
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractSqlQueryDslScopeProvider extends XbaseBatchScopeProvider {
}
