/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.ui;

import de.dc.sql.lang.ui.AbstractSqlQueryDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SqlQueryDslUiModule extends AbstractSqlQueryDslUiModule {
  public SqlQueryDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
