/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang;

import de.dc.sql.lang.SqlQueryDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SqlQueryDslStandaloneSetup extends SqlQueryDslStandaloneSetupGenerated {
  public static void doSetup() {
    new SqlQueryDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
