/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang;

import de.dc.sql.lang.AbstractSqlQueryDslRuntimeModule;

@SuppressWarnings("all")
public class SqlQueryDslRuntimeModule extends AbstractSqlQueryDslRuntimeModule {
}
