/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang;

import de.dc.sql.lang.AbstractSqlQueryDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SqlQueryDslRuntimeModule extends AbstractSqlQueryDslRuntimeModule {
}
