/*
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SqlQueryDslStandaloneSetup extends SqlQueryDslStandaloneSetupGenerated {

	def static void doSetup() {
		new SqlQueryDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
