/**
 * generated by Xtext 2.19.0
 */
package de.dc.sql.lang.ui.labeling;

import org.eclipse.xtext.xbase.ui.labeling.XbaseDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class SqlQueryDslDescriptionLabelProvider extends XbaseDescriptionLabelProvider {
}
